version: '3.7'

services:
  main:
    container_name: app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:7
    volumes:
      - redis:/data
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  pgdata:
